server:
  port: 80

# thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5
    cache: false

  ###data-source
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: musha@1027

  ### jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true